name: Deploy to GitHub Pages # Name of your workflow

on:
  push:
    branches:
      - main # This workflow runs when changes are pushed to the 'main' branch

  # Allows you to run this workflow manually from the Actions tab in GitHub
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest # Specifies the type of runner (virtual machine) to use

    steps:
    - name: Checkout Repository # Step 1: Get your code onto the runner
      uses: actions/checkout@v4 # Uses the official GitHub action for checking out code

    - name: Deploy to GitHub Pages # Step 2: Deploy your site
      uses: peaceiris/actions-gh-pages@v4 # Uses the peaceiris GitHub Pages deployment action
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }} # Uses the automatically provided GitHub token for authentication
        # IMPORTANT: This tells the action that your website files are inside the 'src' folder
        # The contents of 'src' will be copied to the root of the 'gh-pages' branch
        publish_dir: ./src
        # Optional: Explicitly define the branch to publish to (default is gh-pages)
        # It's good practice to be explicit.
        publish_branch: gh-pages
