      - name: Deploy to Kubernetes
        run: |
          cat <<EOF | kubectl apply --validate=false -f -
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: suffutube-deployment
            labels:
              app: suffutube
          spec:
            replicas: 1
            selector:
              matchLabels:
                app: suffutube
            template:
              metadata:
                labels:
                  app: suffutube
              spec:
                containers:
                  - name: suffutube-container
                    image: sufiyanhub/suffutube:latest
                    ports:
                      - containerPort: 80
          ---
          apiVersion: v1
          kind: Service
          metadata:
            name: suffutube-service
          spec:
            type: NodePort
            selector:
              app: suffutube
            ports:
              - port: 80
                targetPort: 80
                nodePort: 32080
          EOF
