name: CI/CD Pipeline - Docker + Slack Notification

on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  IMAGE_NAME: sufiyanhub/youtube-deployment

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: docker build -t $IMAGE_NAME:latest -f ./src/Dockerfile ./src

      - name: Push Docker image
        run: docker push $IMAGE_NAME:latest

  notify-slack:
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
      - name: Notify via AWS Lambda
        run: |
          curl -X POST "$LAMBDA_FUNCTION_URL" \
          -H "Content-Type: application/json" \
          -d '{
            "message": "✅ Docker image pushed to Docker Hub: '${{ env.IMAGE_NAME }}:latest'"
          }'

        env:
          LAMBDA_FUNCTION_URL: ${{ secrets.LAMBDA_FUNCTION_URL }}
